### ISSUE TITLE
An error occurs in the log during the initial startup of the process from the entity editor controller

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/bpm#35]
### Environment

- Platform version: 6.9-SNAPSHOT
- Client type: Web
- Browser: Firefox
- Database: HSQLDB
- Operating system: Windows

### Description of the bug or enhancement
1) Create the entity Contract from the BPM Documentation: https://doc.cuba-platform.com/bpm-6.9/bpm.html#qs_data_model_creation
2) Create a simple process model in the application
![изображение.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/bb9b492c-6433-4048-ab4b-ef7161a50a9b)
3) Deploy the process
4) Create a new Contract, click the button "Start process"
5) A message appears at the bottom right of the screen indicating that the contract has been successfully saved
6) Then a message appears "Process started", then "Access denied"
![изображение.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/f5236d42-7f6c-4ac6-a1cd-e61395faab1d)
7) An error occurs in the app.log (see the attach)
8) However if you save the newly created entity first and then start a process for it, this process will be started ok

app.log:
2018-07-06 16:51:34.613 DEBUG [http-nio-8080-exec-22/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - loadList: metaClass=bpm$ProcAttachment, view=com.haulmont.bpm.entity.ProcAttachment/procAttachment-browse, query=select a from bpm$ProcAttachment a where a.procInstance.entity.entityId = :ds_contractDs order by a.createTs, max=10000
2018-07-06 16:51:36.166 DEBUG [http-nio-8080-exec-12/app/admin] com.haulmont.cuba.web.gui.WebWindow - Validation failed: com.haulmont.cuba.gui.components.RequiredValueMissingException: Number required
2018-07-06 16:51:38.370 DEBUG [http-nio-8080-exec-18/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - commit: commitInstances=[com.company.bpmdemo.entity.Contract-0ed72831-8d87-57d0-2a48-433a2d706b62 [new]], removeInstances=[]
2018-07-06 16:51:38.375 DEBUG [http-nio-8080-exec-18/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - loadList: metaClass=bpm$ProcAttachment, view=com.haulmont.bpm.entity.ProcAttachment/procAttachment-browse, query=select a from bpm$ProcAttachment a where a.procInstance.entity.entityId = :ds_contractDs order by a.createTs, max=10000
2018-07-06 16:51:38.447 DEBUG [http-nio-8080-exec-18/app-core/admin] com.haulmont.cuba.core.app.RdbmsStore - load: metaClass=bpm$ProcInstance, id=d32cd2cb-fd99-6137-f9c3-758f3e55129c, view=com.haulmont.bpm.entity.ProcInstance/procInstance-full
2018-07-06 16:51:38.471 ERROR [http-nio-8080-exec-18/app/admin] com.haulmont.cuba.web.log.AppLog - Exception in com.haulmont.cuba.web.toolkit.ui.CubaButton: 
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:160) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:444) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:409) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) [vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:361) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:312) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:203) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.23]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:107) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.23]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.23]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) ~[tomcat-coyote.jar:8.5.23]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.23]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-coyote.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) ~[tomcat-coyote.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.23]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	... 38 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in com.haulmont.cuba.web.gui.components.WebButton$$Lambda$88/180140366 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:530) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.vaadin.ui.Button.fireClick(Button.java:377) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	at com.haulmont.cuba.web.toolkit.ui.CubaButton.fireClick(CubaButton.java:54) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.vaadin.ui.Button$1.click(Button.java:54) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	... 43 common frames omitted
Caused by: com.haulmont.cuba.core.global.EntityAccessException: Unable to load entity bpm$ProcInstance-d32cd2cb-fd99-6137-f9c3-758f3e55129c because it has been deleted or access denied
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.reload(DataManagerClientImpl.java:89) ~[cuba-client-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.reload(DataManagerClientImpl.java:74) ~[cuba-client-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.reload(DataManagerClientImpl.java:69) ~[cuba-client-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.reload(DataManagerClientImpl.java:64) ~[cuba-client-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.bpm.gui.procactions.ProcActionsFrame$Initializer.lambda$standard$0(ProcActionsFrame.java:443) ~[bpm-gui-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.bpm.gui.action.ProcAction.fireAfterActionListeners(ProcAction.java:58) ~[bpm-gui-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.bpm.gui.action.StartProcessAction._startProcess(StartProcessAction.java:89) ~[bpm-gui-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.bpm.gui.action.StartProcessAction.actionPerform(StartProcessAction.java:77) ~[bpm-gui-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.gui.components.WebButton.performAction(WebButton.java:45) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:37) ~[cuba-web-6.9-SNAPSHOT.jar:6.9-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) ~[vaadin-server-7.7.13.cuba.9.jar:7.7.13.cuba.9]
	... 49 common frames omitted

**Comment by gorbunkov** [comment]
There was an error in the documentation. See the https://github.com/cuba-platform/documentation/issues/177
