### ISSUE TITLE
UnsupportedOperationException when trying to create or edit bpm entities from the Entity Inspector screen

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/bpm#39]
#### Environment

- Platform version: 7.0.0

#### Description of the bug or enhancement
1. Open Entity Inspector
2. Select Process Instance (bpm$ProcInstance) entity
3. Click Create or Edit

For the Process Task (bpm$ProcTask) and Process Definition (bpm$ProcDefinition) entities, this exception appears only when clicking Edit

**A.R.** Exception will appear

```
java.lang.UnsupportedOperationException: Datasource must support paging
	at com.haulmont.cuba.web.gui.components.WebRowsCount.createDatasourceAdapter(WebRowsCount.java:185)
	at com.haulmont.cuba.web.gui.components.WebRowsCount.setDatasource(WebRowsCount.java:115)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.addTable(EntityInspectorEditor.java:814)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.createDataComponents(EntityInspectorEditor.java:381)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorEditor.init(EntityInspectorEditor.java:192)
	at com.haulmont.cuba.gui.components.AbstractWindow.init(AbstractWindow.java:93)
	at com.haulmont.bali.events.EventHub.publish(EventHub.java:170)
	at com.haulmont.cuba.gui.screen.Screen.fireEvent(Screen.java:133)
	at com.haulmont.cuba.gui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:54)
	at com.haulmont.cuba.web.sys.WebScreens.createScreen(WebScreens.java:219)
	at com.haulmont.cuba.web.sys.WebScreens.create(WebScreens.java:154)
	at com.haulmont.cuba.web.sys.WebScreens.openWindow(WebScreens.java:549)
	at com.haulmont.cuba.gui.screen.compatibility.LegacyFrame.openWindow(LegacyFrame.java:100)
	at com.haulmont.cuba.gui.app.core.entityinspector.EntityInspectorBrowse$CreateAction.actionPerform(EntityInspectorBrowse.java:469)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:60)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by jreznot** [comment]
Will be fixed in https://github.com/cuba-platform/cuba/issues/1497
