### ISSUE TITLE
ScriptTask fails for groovy script

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/bpm#43]
When the process reaches a ScriptTask with groovy script, it fails with the exception:

```
com.haulmont.cuba.core.global.RemoteException:
---
org.activiti.engine.ActivitiException: Can't find scripting engine for 'groovy'
    at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129)
    at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
    at org.springframework.aop.framework.JdkDynamicA
opProxy.invoke(JdkDynamicAopProxy.java:212)
    at com.sun.proxy.$Proxy269.startProcess(Unknown Source)
```

**Comment by haulmont-git** [comment]
Git changesets by `gorbunkov`: 

[ec670b13](https://git.haulmont.com/platform/bpm/commit/ec670b13046cd794048e71f1f551f60074b44eb1) in **master** - ScriptTask fails for groovy script #43
